before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: ipterm
    main: ./util/ipterm/main.go
    ldflags: -s -w
    binary: ipterm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - id: iptclient
    main: ./util/iptclient/main.go
    ldflags: -s -w
    binary: iptclient
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - id: atomicdb
    main: ./util/atomicdb/main.go
    ldflags: -s -w
    binary: atomicdb
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - id: atomic
    main: ./main.go
    ldflags: -s -w
    binary: atomic
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
